spring.application.name=trail-map
spring.config.import=optional:application-secret.properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

server.servlet.context-path=/api

#DB
spring.datasource.url=jdbc:postgresql://localhost:5432/trail_map
spring.datasource.username=postgres
spring.datasource.password={DB_PASSWORD}

app.cors.allowed-origins=${FRONTEND_ORIGIN:http://localhost:5173}
